file-version: 1

database:
  host: localhost # host of your database
  port: 3306 # default port for MariaDB and MySQL
  database: db # name of your database. A database server can contain multiple databases
  user: username
  password: pass

server-name: "Survival"
staffplusplus-compatibility: true