name: ModBox
version: '${version}'
main: phewitch.modbox.ModBox
api-version: 1.20

commands:
  hardcore:
      description: "Enables hardcore for yourself"
  revive:
      description: "Revives another player"